name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      INSTALLER_DIR: src\RhinoInside.Revit.Setup\bin\x64\Release
      S3_BUCKET: files.na.mcneel.com
      S3_INSTALLER_PATH: rhino.inside/revit/test/dujour
      S3_UPDATE_PATH: rhino.inside/revit/test/update

    steps:
      - uses: actions/checkout@v2
      
#       - uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '5.0.x'

      - uses: microsoft/setup-msbuild@v1

      - run: msbuild script\cibuild.msbuild -t:Compile
      
      # TODO: sign dlls
      
      - run: msbuild script\cibuild.msbuild -t:BuildInstaller
        id: installer
      
      # TODO: sign installer
      
      - name: Rename installer
        run: |
          $orig = "RhinoInside.Revit.msi"
          $new = "RhinoInside.Revit_${{ steps.installer.outputs.build_number }}.msi"
          cd "src\RhinoInside.Revit.Setup\bin\x64\Release"
          Write-Host "$orig -> $new"
          mv "$orig" "$new"
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Publish installer
        id: publish
        run: |
          $filename = "RhinoInside.Revit_${{ steps.installer.outputs.build_number }}.msi"
          $key = "${{ env.S3_INSTALLER_PATH }}/${filename}"
          $file = "${{ env.INSTALLER_DIR }}\${filename}"
          $url = "https://files.mcneel.com/${key}"
          
          Write-Host "::set-output name=download_url::${url}"

          Write-Host "Uploading to https://files.mcneel.com/${key}"
          aws s3 cp $file s3://${{ env.S3_BUCKET }}/$key -acl public-read
      
      - name: Write update.xml
        run: |
          $url = "${{ steps.publish.outputs.download_url }}"
          msbuild script\cibuild.msbuild -t:WriteUpdateXml -p:"Version=${{ steps.installer.outputs.build_number }};DownloadUrl=$url"

#       - name: Before publish
#         run: |
#           $version = "%build.number%"
#           $major = $version.split(".")[0]
#           Write-Host "Version '$version' has major number: $major"
#           Write-Host "##teamcity[setParameter name='releaseMajor' value='$major']"

#       - name: Publish update.xml
#         run: |
#           $file = "script/update.xml"
#           #$key = "rhino.inside.revit/updates/1.0/daily.xml"
#           $key = "%s3UpdateKey%"
#           $url = "%updateXmlUrl%"
#           Write-Host "Uploading to $url"
#           Write-S3Object -BucketName %s3Bucket% -File $file -Key $key -CannedACLName public-read -HeaderCollection @{"Cache-Control" = "no-cache"}
