name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      INSTALLER_DIR: src\RhinoInside.Revit.Setup\bin\x64\Release
      S3_BUCKET: files.na.mcneel.com
      S3_INSTALLER_PATH: rhino.inside/revit/test/dujour
      S3_UPDATE_PATH: rhino.inside/revit/test/update

    steps:
      - uses: actions/checkout@v2
      
#       - uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '5.0.x'

      - uses: microsoft/setup-msbuild@v1

      - run: msbuild script\cibuild.msbuild -t:Compile -v:m
      
      # TODO: sign dlls
      
      - run: msbuild script\cibuild.msbuild -t:BuildInstaller -v:m
        id: installer
        # uses workflow command to output version as "build_number"
      
      # TODO: sign installer
      
      - name: Rename installer
        run: |
          $orig = "RhinoInside.Revit.msi"
          $new = "RhinoInside.Revit_${{ steps.installer.outputs.build_number }}.msi"
          cd "src\RhinoInside.Revit.Setup\bin\x64\Release"
          Write-Host "$orig -> $new"
          mv "$orig" "$new"
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Publish installer
        id: publish
        run: |
          $filename = "RhinoInside.Revit_${{ steps.installer.outputs.build_number }}.msi"
          $key = "${{ env.S3_INSTALLER_PATH }}/${filename}"
          $file = "${{ env.INSTALLER_DIR }}\${filename}"
          $url = "https://files.mcneel.com/${key}"
          
          echo "::set-output name=download_url::${url}"

          echo "::group::Uploading to $url"
          aws s3 cp $file s3://${{ env.S3_BUCKET }}/$key --acl public-read
          echo "::endgroup::"
      
      - name: Write update.xml
        run: |
          $version = "${{ steps.installer.outputs.build_number }}"
          $url = "${{ steps.publish.outputs.download_url }}"
          msbuild script\cibuild.msbuild -t:WriteUpdateXml -p:"Version=$version;DownloadUrl=$url"

#       - name: Before publish
#         run: |
#           $version = "${{ steps.installer.outputs.build_number }}"
#           $major = $version.split(".")[0]
#           echo "Version '$version' has major number: $major"
#           echo "release_major=%major" >> $GITHUB_ENV

      - name: Publish update.xml
        run: |
          $major = "${{ steps.installer.outputs.build_number }}".split(".")[0]
          $file = "script/update.xml"
          $key = "${{ env.S3_UPDATE_PATH }}/${major}/daily.xml"
          $url = "https://files.mcneel.com/${key}"

          echo "::group::Uploading to $url"
          aws s3 cp $file s3://${{ env.S3_BUCKET }}/$key --acl public-read --cache-control no-cache
          echo "::endgroup::"
