name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - run: dotnet msbuild script\cibuild.msbuild -t:Compile
      
      # TODO: sign dlls
      
      - run: dotnet msbuild script\cibuild.msbuild -t:BuildInstaller
      
      # TODO: sign installer
